# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Heiko Braun
tagline:             'Software Engineer'
description:         ''
#url:                 http://heiko-braun.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Heiko Braun
  url:               https://twitter.com/heiko_braun
  email:

# Custom vars
version:             1.0.0
